name: ddd_flutter_app
description: DDD compliant Flutter app with BLoC/Cubit state management
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  dartz: ^0.10.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  freezed: ^2.5.7
  get_it: ^8.2.0
  graphql_flutter: ^5.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  json_serializable: ^6.9.0
  retrofit: ^4.5.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.13
  flutter_test:
    sdk: flutter
  freezed_annotation: ^2.4.4
  injectable_generator: ^2.6.2
  mocktail: ^1.0.4
  retrofit_generator: ^9.1.5
  very_good_analysis: ^9.0.0

flutter:
  uses-material-design: true
  generate: true
