# Project Configuration
# This file contains all configurable project settings
# Run the configure script to apply these changes

project:
  name: "My Awesome App"
  description: "A fantastic Flutter application"
  version: "1.0.0"
  build_number: "1"
  
  # Package name (used for Android and iOS bundle identifier)
  package_name: "com.mycompany.myawesomeapp"
  
  # App display name (shown on device)
  display_name: "My Awesome App"
  
  # Company/Organization details
  company:
    name: "My Company"
    website: "https://mycompany.com"
    email: "contact@mycompany.com"
  
  # iOS specific settings
  ios:
    bundle_identifier: "com.mycompany.myawesomeapp"
    team_id: "YOUR_TEAM_ID"  # Replace with your actual team ID
    deployment_target: "12.0"
    minimum_version: "12.0"
    
  # Android specific settings
  android:
    application_id: "com.mycompany.myawesomeapp"
    min_sdk_version: "21"
    target_sdk_version: "34"
    compile_sdk_version: "34"
    
  # Flutter settings
  flutter:
    sdk_version: "^3.5.0"
    
  # Build flavors
  flavors:
    production:
      name: "Production"
      suffix: ""
      app_name: "My Awesome App"
    staging:
      name: "Staging"
      suffix: ".stg"
      app_name: "[STG] My Awesome App"
    development:
      name: "Development"
      suffix: ".dev"
      app_name: "[DEV] My Awesome App"
      
  # Features and capabilities
  features:
    analytics: true
    crash_reporting: true
    push_notifications: false
    biometric_auth: false
    
  # Dependencies (can be toggled on/off)
  dependencies:
    bloc: true
    dio: true
    shared_preferences: true
    graphql: false
    retrofit: false
